require "rake"
require "rake/clean"

FLASH_HXML = FileList.new("flash/*/swf.hxml")

FLASH = FLASH_HXML.each_with_index.map do |flash_hxml, index|
  dir = File.dirname(flash_hxml)
  flash = flash_hxml.sub("swf.hxml", "bin/main.swf")

  title = flash.split("/")[1].split("_")[0]

  task flash => flash_hxml do
    Dir.chdir(dir) do
      sh "haxe #{File.basename(flash_hxml)}"
    end
  end

  task "#{flash}.dump" => flash_hxml do
    Dir.chdir(dir) do
      sh "haxe #{File.basename(flash_hxml)} -D dump=pretty"
    end
  end

  task "#{flash}.test" => flash do
    Dir.chdir(dir) do
      sh "open bin/main.swf"
    end
  end

  task "#{flash}.debug" => flash do
    Dir.chdir(dir) do
      sh "fdb bin/main.swf"
    end
  end

  CLEAN << File.join(dir, "dump")
  CLOBBER << File.join(dir, "bin")
  CLOBBER << File.join(dir, "doc")

  desc "test #{flash}"
  task title => "#{flash}.test"

  desc "dump #{flash}" if index == 0
  task "#{title}.dump"=> "#{flash}.dump"

  desc "build #{flash}" if index == 0
  task "#{title}.build" => "#{flash}"

  desc "debug #{flash}" if index == 0
  task "#{title}.debug"=> "#{flash}.debug"

  "#{title}.build"
end

task "all.build" => FLASH

task "default" => "all.build"
